capstone/discussion/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls'))
]

capstone/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.index, name = "index"),

    # tasks
    path('task/add-task/', views.add_task, name="add_task"),
    path('task/<int:todoitem_id>/', views.todoitem, name = "viewtodoitem"),
    path('task/<int:todoitem_id>/edit', views.update_task, name="update_task"),
    path('task/<int:todoitem_id>/delete', views.delete_task, name="delete_task"),

    # events section
    path('event/add-event/', views.add_event, name="add_event"),
    path('event/<int:eventitem_id>/', views.eventitem, name = "vieweventitem"),
    path('event/<int:eventitem_id>/edit', views.update_event, name="update_event"),
    path('event/<int:eventitem_id>/delete', views.delete_event, name="delete_event"),


    # accounts section 
    path('change-password/', views.changePassword, name = "change_password"),
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name = "logout"),
    path('register/', views.register, name = "register")
]

capstone/todolist/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ToDoItem(models.Model):
    # CharField = String value
    # DateTimeField = DateTime 
    task_name = models.CharField(max_length = 50)
    description = models.CharField(max_length = 200)
    status = models.CharField(max_length = 50, default = "Pending")
    date_created = models.DateTimeField("Date Created")
    # Adding a user_id to the ToDoItem table, which is a foreign key connected to the Users table
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = "")

class EventItem(models.Model):
    event_name = models.CharField(max_length = 50)
    description = models.CharField(max_length = 200)
    status = models.CharField(max_length = 50, default = "Pending")
    event_date = models.DateField("Event Date")
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = "")

capstone/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Username", max_length = 20)
    password = forms.CharField(label = "Password", max_length = 20)


class AddTaskForm(forms.Form):
    task_name = forms.CharField(label = "Task Name", max_length = 50)
    description = forms.CharField(label = "Description", max_length = 200)

class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label = "Task Name", max_length = 50)
    description = forms.CharField(label = "Description", max_length = 200)
    status = forms.CharField(label="Status", max_length=50)

class AddEventForm(forms.Form):
    event_name = forms.CharField(label = "Event Name", max_length = 50)
    description = forms.CharField(label = "Description", max_length = 200)
    event_date = forms.DateField(label = "Event Date")

class UpdateEventForm(forms.Form):
    event_name = forms.CharField(label = "Event Name", max_length = 50)
    description = forms.CharField(label = "Description", max_length = 200)
    event_date = forms.DateField(label = "Event Date")
    status = forms.CharField(label="Status", max_length=50)

capstone/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, AddEventForm, UpdateEventForm

# We import the built-in 'User' model to be able to operations to the built-in  Users table from Django
from django.contrib.auth.models import User
from .models import ToDoItem, EventItem

# Create your views here.
def index(request):
    todoitem_list = ToDoItem.objects.filter(user_id = request.user.id)
    eventitem_list = EventItem.objects.filter(user_id = request.user.id)

    template = loader.get_template('todolist/index.html')
    context = {
        'todoitem_list' :  todoitem_list,
        'eventitem_list' : eventitem_list,
        'user' : request.user
    }
    # return HttpResponse(template.render(context, request))
    return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
    # 'model_to_dict' function translates a data model into a python dictionary/object
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))  

def register(request):
    users = User.objects.all()
    
    is_user_registered = False

    # Loops through each existing user and checks if they already exist in the table
    for individual_user in users:
        if individual_user.username == "johndoe":
            is_user_registered = True
            break

    # The context 'is_user_registered' is put after the for loop in order for it to get the updated value if 'for' loop above equals to True.
    context = {
        "is_user_registered" : is_user_registered
    }

    if is_user_registered == False:
        # 1. Creating a new instance of the User model
        user = User()

        # 2. Assign data values to each property of the model
        user.username = 'johndoe'
        user.first_name = 'John'
        user.last_name = 'Doe'
        user.email = 'johndoe@mail.com'
        user.set_password("john1234")
        user.is_staff = False
        user.is_active = True

        # 3. Save the new instance of a new user into the database
        user.save()

        # The context will be the data that will be passed to the template
        context = {
            "first_name" : user.first_name,
            "last_name" : user.last_name
        }

    return render(request, "todolist/register.html", context)

def changePassword(request):
    is_user_authenticated = False

    user = authenticate(username = "johndoe", password="johndoe1")

    print(user)

    if user is not None:
        authenticated_user = User.objects.get(username="johndoe")
        authenticated_user.set_password("johndoe1")
        authenticated_user.save()

        is_user_authenticated = True

    context = {
        "is_user_authenticated" : is_user_authenticated
    }

    return render(request, "todolist/change_password.html", context)

def login_view(request):
    context = {}

    if request.method == 'POST':
        # request.POST contains all the fields coming from the Login.html
        form = LoginForm(request.POST)

        if form.is_valid() == False:
            #if you use LoginForm() without passing any data, it will just return the properties 'username' and 'password'without data/value
            form = LoginForm()

        else:
            # we use the 'form.cleaned_data[]' to get the properties that we need from the from
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            context = {
                "username":username,
                "password":password
            }

            if user is not None:
                # The 'login' function saves the user's ID in Django's session. The request will be the one that handles the user's data and we can access the user by using 'request.user'.
                login(request, user)
                return redirect("todolist:index")
            else:
                context = {
                    'error' : True
                }

    return render(request, "todolist/login.html", context)

def logout_view(request):
    logout(request)
    return redirect("todolist:index")

def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name) 

			if not duplicates:
				ToDoItem.objects.create(
					task_name = task_name,
					description = description,
					date_created = timezone.now(),
                    user_id =  request.user.id
				)

				return redirect('todolist:index')

			else: 
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):
     # Returns a queryset
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    context = {
        "user": request.user,
        "todoitem_id": todoitem_id,
        # Accessing the first element is necessary because the "ToDoItem.objects.filter()" method returns a queryset
        "task_name": todoitem[0].task_name,
        "description": todoitem[0].description,
        "status": todoitem[0].status
    }

    if request.method == 'POST':

        form = UpdateTaskForm(request.POST)

        if form.is_valid() == False:

            form = UpdateTaskForm()

        else:

            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']
            
            if todoitem:

                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    todoitem.delete()

    return redirect("todolist:index")

def eventitem(request, eventitem_id):

    # 'model_to_dict' function translates a data model into a python dictionary/object
	eventitem = get_object_or_404(EventItem, pk=eventitem_id)

	return render(request, "todolist/eventitem.html", model_to_dict(eventitem))

def add_event(request):
    context = {}

    if request.method == 'POST':
        form = AddEventForm(request.POST)

        if form.is_valid() == False:
            form = AddEventForm()

        else:
            event_name = form.cleaned_data['event_name']
            event_date = form.cleaned_data['event_date']
            description = form.cleaned_data['description']

            duplicates = EventItem.objects.filter(event_name=event_name) 

            if not duplicates:
                EventItem.objects.create(
					event_name = event_name,
					description = description,
                    event_date = event_date,
                    user_id =  request.user.id
				)

                return redirect('todolist:index')

            else: 
                context = {
					"error": True
				}

    return render(request, "todolist/add_event.html", context)

def update_event(request, eventitem_id):
     # Returns a queryset
    eventitem = EventItem.objects.filter(pk=eventitem_id)

    context = {
        "user": request.user,
        "eventitem_id": eventitem_id,
        # Accessing the first element is necessary because the "ToDoItem.objects.filter()" method returns a queryset
        "event_name": eventitem[0].event_name,
        "description": eventitem[0].description,
        "status": eventitem[0].status,
        "event_date": eventitem[0].event_date
    }

    if request.method == 'POST':

        form = UpdateEventForm(request.POST)

        if form.is_valid() == False:

            form = UpdateEventForm()

        else:

            event_name = form.cleaned_data['event_name']
            description = form.cleaned_data['description']
            event_date = form.cleaned_data['event_date']
            status = form.cleaned_data['status']
            
            if eventitem:

                eventitem[0].event_name = event_name
                eventitem[0].description = description
                eventitem[0].event_date = event_date
                eventitem[0].status = status

                eventitem[0].save()
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/update_event.html", context)

def delete_event(request, eventitem_id):
    eventitem = EventItem.objects.filter(pk=eventitem_id)

    eventitem.delete()

    return redirect("todolist:index")

capstone/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add an Event{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add an Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate event found</p>
				{% endif %}
				<form action="{% url 'todolist:add_event' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="event_name">Event Name:</label>
						<input 
						    type="text" 
						    class="form-control" 
						    id="event_name"
						    name="event_name"
						    value="{{ event_name }}"
						    maxlength="50"
						    required 
						>
					</div>
					<div class="mb-3">
						<label for="description">Description:</label>
						<input 
						    type="text" 
						    class="form-control" 
						    id="description"
						    name="description"
						    value="{{ description }}"
						    required 
						>
					</div>
					<div class="mb-3">
						<label for="event_date">Event Date:</label>
						<input 
						    type="date" 
						    class="form-control" 
						    id="event_date"
						    name="event_date"
						    value="{{ event_date }}"
						    required 
						>
					</div>
					<div class="text-center">
						<input type="submit" class="btn btn-success" value="Add Event">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

capstone/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add a new Task{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add a Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="task_name">Task Name:</label>
						<input 
						    type="text" 
						    class="form-control" 
						    id="task_name"
						    name="task_name"
						    value="{{ task_name }}"
						    maxlength="50"
						    required 
						>
					</div>
					<div class="mb-3">
						<label for="description">Description:</label>
						<input 
						    type="text" 
						    class="form-control" 
						    id="description"
						    name="description"
						    value="{{ description }}"
						    required 
						>
					</div>
					<div class="text-center">
						<input type="submit" class="btn btn-success" value="Add Task">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

capstone/todolist/templates/todolist/change_password.html
{% if user_is_authenticated == False %}
    <h1>Invalid User Credentials</h1>
    <p>Check if the username and password is correct.</p>
{% else %}
    <h1>User Password Successfully Updated!</h1>
    <p>The password has been updated</p>
{% endif %}

capstone/todolist/templates/todolist/eventitem.html
{% extends 'base.html' %}

{% block title %}Add a new Task{% endblock %}

{% block content %}
<div class="text-center my-3">

    <h2>Task Name:</h2>
    <p>{{event_name}}</p>
    <h3>Description:</h3>
    <p>{{description}}</p>
    <h3>Event Date:</h3>
    <p>{{event_date}}</p>
    <h3>Status:</h3>
    <p>{{status}}</p>


    <button class = "btn btn-lg btn-primary mx-1 text-decoration-none">
        <a href = "{% url 'todolist:update_event' id %}" class="text-light text-decoration-none">Edit Task</a>
    </button>
    <button class = "btn btn-lg btn-danger mx-1 text-decoration-none">
        <a href = "{% url 'todolist:delete_event' id %}" class="text-light text-decoration-none">Delete Task</a>
    </button>
    <button class = "btn btn-lg btn-warning mx-1 text-decoration-none">
        <a href = "{% url 'todolist:index' %}" class="text-light text-decoration-none">Go Back</a>
    </button>
</div>

{% endblock %}

capstone/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
	{% if user.is_anonymous == True %}

		<h1 class = "text-center my-3">You are not authorized to access this page.</h1>
		<p class = "text-center">Kindly login <a href = "login">here</a></p>

	{% elif user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class="container">
			<!-- Task index -->
			<div class="row text-center">
				<h3 class="mb-3">My Tasks:</h3>
				<ul class="list-group col-lg-2 offset-lg-5">
					{% if todoitem_list %}
						{% for todoitem in todoitem_list %}
							<a href="{% url 'todolist:viewtodoitem' todoitem.id%}" class="text-decoration-none">
								<li class="list-group-item">{{todoitem.task_name}}</li>
							</a>
						{% endfor %}
					{% else %}
						<p>No tasks have been created.</p>	
					{% endif %}
				</ul>
			</div>

			<!-- Event Index -->
			<div class="row text-center">
				<h3 class="mb-3">My Events:</h3>
				<ul class="list-group col-lg-2 offset-lg-5">
					{% if eventitem_list %}
						{% for eventitem in eventitem_list %}
							<a href="{% url 'todolist:vieweventitem' eventitem.id%}" class="text-decoration-none">
								<li class="list-group-item">{{eventitem.event_name}}</li>
							</a>
						{% endfor %}
					{% else %}
						<p>No events have been created.</p>	
					{% endif %}
				</ul>
			</div>
		</div>
	{% endif %}
{% endblock %}

capstone/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				{% if is_user_authenticated == False %}
					<h1>Something went wrong</h1>
					<p>Please contact your administrator.</p>

					<a href="{% url 'todolist:index' %}">Back to index page</a>
				{% endif %}

				<form action="{% url 'todolist:login' %}" method="post">
					<!-- 
						CSRF Token (Cross Site Request Forgeries)
						-For making sure that the form request is coming from the same django project. If not, django will block the request.

						Note: ALL forms in django need a csrf_token.
					-->
					{% csrf_token %}

					<div class="mb-3">
						<label for="username">Username:</label>
						<input 
							type="text" 
							class="form-control" 
							id="username" 
							maxlength="20" 
							name="username" 
							value="{{ username }}" 
							required
						>
					</div>
					<div class="mb-3">
						<label for="password">Password:</label>
						<input 
							type="password" 
							class="form-control" 
							id="password" 
							maxlength="20" 
							name="password" 
							value="{{ password }}" 
							required
						>
					</div>
					<div class="text-center">
						<input type="submit" class="btn btn-success" value="Login">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

capstone/todolist/templates/todolist/register.html
{% if is_user_registered == True %}
    <h1>Duplicate User found</h1>
    <p>A duplicate user has been found, user creation unsuccessful</p>

{% else %}
    <h1>User Successfully Created</h1>
    <p>The account for {{first_name}} {{last_name}} has been created!</p>

{% endif %}

capstone/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Add a new Task{% endblock %}

{% block content %}
<div class="text-center my-3">

    <h2>Task Name:</h2>
    <p>{{task_name}}</p>
    <h3>Description:</h3>
    <p>{{description}}</p>
    <h3>Status:</h3>
    <p>{{status}}</p>


    <button class = "btn btn-lg btn-primary mx-1 text-decoration-none">
        <a href = "{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
    </button>
    <button class = "btn btn-lg btn-danger mx-1 text-decoration-none">
        <a href = "{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
    </button>
    <button class = "btn btn-lg btn-warning mx-1 text-decoration-none">
        <a href = "{% url 'todolist:index' %}" class="text-light text-decoration-none">Go Back</a>
    </button>
</div>

{% endblock %}

capstone/todolist/templates/todolist/update_event.html
{% extends 'base.html' %}

	{% block title %}Update Event{% endblock %}

	{% block content %}
		{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Task</h1>
					{% if error == True %}
						<p class="text-danger">Task not found</p>
					{% endif %}
					<form action="{% url 'todolist:update_event' eventitem_id %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="event_name">Event Name: </label>
						    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
							<label for="event_date">Event Date:</label>
							<input 
								type="date" 
								class="form-control" 
								id="event_date"
								name="event_date"
								value="{{ event_date }}"
								required 
							>
						</div>

						<div class="mb-3">
						    <label for="status">Status: </label>
						    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Event">
						</div>

					</form>
				</div>
			</div>
		</div>
		{% else %}
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		{% endif %}
	{% endblock %}

capstone/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

	{% block title %}Update Task{% endblock %}

	{% block content %}
		{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Task</h1>
					{% if error == True %}
						<p class="text-danger">Task not found</p>
					{% endif %}
					<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="task_name">Task Name: </label>
						    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
						    <label for="status">Status: </label>
						    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Task">
						</div>

					</form>
				</div>
			</div>
		</div>
		{% else %}
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		{% endif %}
	{% endblock %}